### PR TITLE
Add flutter-pub-roller-bot to list of auto_approval_accounts

### PR DESCRIPTION
**Pull request by christopherfujino**
Part of https://github.com/flutter/flutter/issues/129847

Add bot account: https://github.com/flutter-pub-roller-bot

### CODE REVIEW

**Comment by ricardoamador** [comment]
By adding this to the $org/.github repo this will apply to all flutter repos. Is that what is intended here?

**Review by ricardoamador — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@ricardoamador I would be ok with moving this to the framework repo config--however, from reading the source, it looked to me like only the org-level config was checked when determining the auto approval accounts via:

1. https://github.com/flutter/cocoon/blob/main/auto_submit/lib/service/approver_service.dart#L29
2. https://github.com/flutter/cocoon/blob/main/auto_submit/lib/service/config.dart#L121
3. https://github.com/flutter/cocoon/blob/main/auto_submit/lib/configuration/repository_configuration_manager.dart#L47
4. https://github.com/flutter/cocoon/blob/main/auto_submit/lib/configuration/repository_configuration_manager.dart#L68

**Comment by ricardoamador** [comment]
If you add the allow-override flag it will check the local repo. But it might not matter if this bot only operates in the flutter repo autosubmit won't care unless it is in flutter. No big deal.

**Comment by christopherfujino** [comment]
Ahh, I see, looks like it grabs it here: https://github.com/flutter/cocoon/blob/main/auto_submit/lib/configuration/repository_configuration_manager.dart#L85C17-L85C17

**Pull request merged**
