### PR TITLE
Update README.md with necessary stack.

### PR DESCRIPTION
**Pull request by Anyaoha**
Update README.md with the necessary stack used in the project development. 
This will help users to EASILY visualize the languages used in the entire project without trying to figure that out per repository. 
Also will help contributors easily visualize which languages are needed and can be used to further support the project.

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Anyaoha** [comment]
My CLA as a contributors is complete! Not sure why this the block.

**Comment by Anyaoha** [comment]
> Wondering if we really need this since GitHub already provide this information.
> 
> If we are going to merge this, then we should reference the main website of each language listed whenever possible.

Just added the main websites to the top languages!

**Comment by Hixie** [comment]
Thanks for your contribution. We have this kind of information on our main web site (flutter.dev) but I don't think it's super useful in the README for this repo, so I'm going to close the PR. Thanks again though!

**Comment by Anyaoha** [comment]
3FC2F1CE-12B3-4F72-8ECF-BAF75C271576

**Comment by Anyaoha** [comment]
@Hixie you’re really unappreciative of my contribution. Instead of accepting my PR since September 5. You just copied my contribution yourself and merged it into master on September 30th without giving me contribution credits. Now you’re here commenting that you already have such info in the repo. @pedromassango @kevmoo @darrenaustin 
This is such a bad and appalling dev behaviour in an open source community. I’d raise this up in the community! 👎🏾👎🏾👎🏾

**Comment by kevmoo** [comment]
I'm sorry you're upset, @Anyaoha – but (in my opinion) your bar for "bad and appalling" seems a bit off. @Hixie has been an amazing champion of civility in our community publicly and privately since the beginning. We all need to be careful attributing malice to – perhaps – a misunderstanding.

**Comment by Anyaoha** [comment]
@kevmoo would you say @Hixie behaviour in this case is acceptable? 

Why copy my contribution and make not efforts to give me credit. 
this is guy. You can trace changes. See it for yourself. 

So would you say you this behaviour is acceptable?

**Comment by kevmoo** [comment]
Less than ideal? Perhaps. We are talking about a markdown file in an obscure repository, right? A simple reminder to give credit may have been more "proportionate". Calling @Hixie out? bringing in other contributors? Calls of "appalling" with 👎 👎 👎 ?

Respect should go both ways.

**Comment by Anyaoha** [comment]
Okay @kevmoo. I’d do as you’ve mentioned. 

Please take this as a reminder to give me credit and being a contributor. 
I’d hope this would be done. Thanks

**Comment by Hixie** [comment]
> You just copied my contribution yourself and merged it into master on September 30th without giving me contribution credits

o_O

The changes you pointed to do not include anything like this PR...

**Pull request closed without merging**
